"""Tests for cereal/services.py - service definitions."""
from cereal.services import (
  QueueSize, Service, SERVICE_LIST, build_header,
)


class TestQueueSize:
  """Test QueueSize enum."""

  def test_big_value(self):
    """Test BIG queue size is 10MB."""
    assert QueueSize.BIG == 10 * 1024 * 1024

  def test_medium_value(self):
    """Test MEDIUM queue size is 2MB."""
    assert QueueSize.MEDIUM == 2 * 1024 * 1024

  def test_small_value(self):
    """Test SMALL queue size is 250KB."""
    assert QueueSize.SMALL == 250 * 1024

  def test_ordering(self):
    """Test queue sizes are correctly ordered."""
    assert QueueSize.BIG > QueueSize.MEDIUM
    assert QueueSize.MEDIUM > QueueSize.SMALL


class TestService:
  """Test Service class."""

  def test_init_with_defaults(self):
    """Test Service initialization with defaults."""
    s = Service(should_log=True, frequency=20.0)

    assert s.should_log is True
    assert s.frequency == 20.0
    assert s.decimation is None
    assert s.queue_size == QueueSize.SMALL

  def test_init_with_decimation(self):
    """Test Service initialization with decimation."""
    s = Service(should_log=True, frequency=100.0, decimation=10)

    assert s.decimation == 10

  def test_init_with_queue_size(self):
    """Test Service initialization with custom queue size."""
    s = Service(should_log=False, frequency=20.0, queue_size=QueueSize.BIG)

    assert s.queue_size == QueueSize.BIG

  def test_init_all_params(self):
    """Test Service initialization with all parameters."""
    s = Service(
      should_log=False,
      frequency=50.0,
      decimation=5,
      queue_size=QueueSize.MEDIUM
    )

    assert s.should_log is False
    assert s.frequency == 50.0
    assert s.decimation == 5
    assert s.queue_size == QueueSize.MEDIUM


class TestServiceList:
  """Test SERVICE_LIST dictionary."""

  def test_service_list_not_empty(self):
    """Test SERVICE_LIST contains services."""
    assert len(SERVICE_LIST) > 0

  def test_service_list_contains_can(self):
    """Test SERVICE_LIST contains can service."""
    assert 'can' in SERVICE_LIST

  def test_service_list_contains_controlsState(self):
    """Test SERVICE_LIST contains controlsState service."""
    assert 'controlsState' in SERVICE_LIST

  def test_service_list_contains_carState(self):
    """Test SERVICE_LIST contains carState service."""
    assert 'carState' in SERVICE_LIST

  def test_service_list_contains_modelV2(self):
    """Test SERVICE_LIST contains modelV2 service."""
    assert 'modelV2' in SERVICE_LIST

  def test_service_list_values_are_services(self):
    """Test SERVICE_LIST values are Service instances."""
    for name, svc in SERVICE_LIST.items():
      assert isinstance(svc, Service), f"{name} is not a Service"

  def test_can_has_big_queue(self):
    """Test can service has BIG queue size."""
    assert SERVICE_LIST['can'].queue_size == QueueSize.BIG

  def test_controlsState_has_medium_queue(self):
    """Test controlsState has MEDIUM queue size."""
    assert SERVICE_LIST['controlsState'].queue_size == QueueSize.MEDIUM

  def test_deviceState_should_log(self):
    """Test deviceState should_log is True."""
    assert SERVICE_LIST['deviceState'].should_log is True

  def test_roadEncodeIdx_should_not_log(self):
    """Test roadEncodeIdx should_log is False."""
    assert SERVICE_LIST['roadEncodeIdx'].should_log is False

  def test_frequencies_positive(self):
    """Test all frequencies are non-negative."""
    for name, svc in SERVICE_LIST.items():
      assert svc.frequency >= 0, f"{name} has negative frequency"

  def test_high_freq_services(self):
    """Test high-frequency services have correct values."""
    # can, sendcan, controlsState, carState all at 100Hz
    for name in ['can', 'sendcan', 'controlsState', 'carState']:
      assert SERVICE_LIST[name].frequency == 100.0


class TestBuildHeader:
  """Test build_header function."""

  def test_returns_string(self):
    """Test build_header returns a string."""
    result = build_header()
    assert isinstance(result, str)

  def test_includes_autogen_comment(self):
    """Test header includes autogenerated comment."""
    result = build_header()
    assert "AUTOGENERATED" in result

  def test_includes_ifndef_guard(self):
    """Test header includes include guard."""
    result = build_header()
    assert "#ifndef __SERVICES_H" in result
    assert "#define __SERVICES_H" in result
    assert "#endif" in result

  def test_includes_service_struct(self):
    """Test header includes service struct definition."""
    result = build_header()
    assert "struct service" in result

  def test_includes_map_include(self):
    """Test header includes map header."""
    result = build_header()
    assert "#include <map>" in result

  def test_includes_service_entries(self):
    """Test header includes service entries."""
    result = build_header()
    assert '"can"' in result
    assert '"controlsState"' in result
    assert '"carState"' in result

  def test_includes_frequency(self):
    """Test header includes frequency values."""
    result = build_header()
    # can service should have 100.0 frequency
    assert "100.0" in result

  def test_includes_queue_sizes(self):
    """Test header includes queue size values."""
    result = build_header()
    # Should have actual byte values
    assert str(QueueSize.BIG) in result
    assert str(QueueSize.SMALL) in result
